name: YumRush CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    
    strategy:
      matrix:
        node-version: [16.x]
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: TypeScript check
      run: npm run typecheck
    
    - name: Run tests
      run: npm test
      env:
        MONGODB_URI: mongodb://localhost:27017/yumrush_test
        JWT_SECRET: testsecret
  
  frontend-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: TypeScript check
      run: npm run typecheck
    
    - name: Run unit tests
      run: npm test
    
    - name: Build
      run: npm run build
  
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: github.event_name == 'pull_request'
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '4.4'
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Start backend server
      run: |
        cd backend
        npm run init-db &
        npm run dev &
      env:
        MONGODB_URI: mongodb://localhost:27017/yumrush_test
        JWT_SECRET: testsecret
        PORT: 1972
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        working-directory: ./frontend
        start: npm run dev
        wait-on: 'http://localhost:3000, http://localhost:1972'
        wait-on-timeout: 120
        browser: chrome
        record: false
      env:
        CYPRESS_baseUrl: http://localhost:3000